apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: v3i3gg2pk-java-quarkus
  janus-idp.io/tekton: v3i3gg2pk-java-quarkus
  backstage.io/kubernetes-id: v3i3gg2pk-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v3i3gg2pk-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
